FROM 192.168.0.252:5000/sqlrustgo-gate:v5
RUN apk add --no-cache docker-cli
COPY --from=gitea/act_runner:node /usr/local/bin/act_runner /usr/local/bin/act_runner
COPY --from=gitea/act_runner:node /usr/local/bin/run.sh /usr/local/bin/run.sh
ENTRYPOINT ["/usr/local/bin/run.sh"]
