"""Audit checks — independent governance rule verification.

Each check is a pure function that can be reasoned about independently.
These checks do NOT depend on verification_engine.py logic.
"""

import json
import subprocess
import re
from dataclasses import dataclass
from typing import List, Tuple, Optional
from pathlib import Path


# ─────────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────────

BASELINE_PASSED = 226
BASELINE_FAILED = 0
BASELINE_IGNORED = 0
BASELINE_BRANCH = "origin/develop/v2.8.0"


# ─────────────────────────────────────────────────────────────────
# Data structures
# ─────────────────────────────────────────────────────────────────

@dataclass
class CheckResult:
    rule: str
    passed: bool
    message: str
    severity: str  # CRITICAL, HIGH, MEDIUM, LOW, INFO
    evidence: Optional[dict] = None


@dataclass
class AuditReport:
    status: str  # TRUSTED, WEAKENED, COMPROMISED
    checks: List[CheckResult]
    critical_failures: List[str]
    warnings: List[str]
    info: List[str]


# ─────────────────────────────────────────────────────────────────
# Rule Checks (R1-R7, AV1-AV9)
# ─────────────────────────────────────────────────────────────────

def check_r1_test_immutability(repo_root=".") -> CheckResult:
    """R1: No changes in tests/ directory since baseline."""
    result = subprocess.run(
        ["git", "diff", "--name-only", f"{BASELINE_BRANCH}...HEAD"],
        capture_output=True,
        text=True,
        cwd=repo_root
    )
    changed = [l for l in result.stdout.splitlines() if l.startswith("tests/")]

    return CheckResult(
        rule="R1",
        passed=len(changed) == 0,
        message="No test files modified" if not changed else f"R1 VIOLATED: {len(changed)} test file(s) modified",
        severity="CRITICAL",
        evidence={"changed_files": changed, "baseline": BASELINE_BRANCH}
    )


def check_r2_ignore_injection(repo_root=".") -> CheckResult:
    """R2: No new #[ignore] added since baseline."""
    result = subprocess.run(
        ["git", "diff", f"{BASELINE_BRANCH}...HEAD", "--", "*.rs"],
        capture_output=True,
        text=True,
        cwd=repo_root
    )
    new_ignores = []
    for line in result.stdout.splitlines():
        if line.startswith("+") and "#[ignore" in line:
            new_ignores.append(line.strip())

    return CheckResult(
        rule="R2",
        passed=len(new_ignores) == 0,
        message="No new #[ignore]" if not new_ignores else f"R2 VIOLATED: {len(new_ignores)} new #[ignore] found",
        severity="CRITICAL",
        evidence={"new_ignores": new_ignores, "baseline": BASELINE_BRANCH}
    )


def check_r3_proof_provenance(proof: dict) -> CheckResult:
    """R3: Proof was generated by CI, not declared by PR."""
    valid_gen = proof.get("generated_by") == "verification_engine.py"
    valid_src = proof.get("source") == "CI execution (not PR declaration)"

    return CheckResult(
        rule="R3",
        passed=valid_gen and valid_src,
        message="Proof is CI-provenance" if valid_gen else "R3 VIOLATED: Proof not CI-generated",
        severity="CRITICAL",
        evidence={
            "generated_by": proof.get("generated_by"),
            "source": proof.get("source"),
            "valid": valid_gen and valid_src
        }
    )


def check_r4_full_execution(passed: int, failed: int, ignored: int) -> CheckResult:
    """R4: All tests ran and passed."""
    all_passed = passed == BASELINE_PASSED and failed == BASELINE_FAILED
    no_ignored = ignored == BASELINE_IGNORED

    return CheckResult(
        rule="R4",
        passed=all_passed and no_ignored,
        message=f"All tests passed ({passed}/{BASELINE_PASSED})" if all_passed else f"R4 FAILED: {failed} failed, {ignored} ignored",
        severity="CRITICAL",
        evidence={"passed": passed, "failed": failed, "ignored": ignored, "required": {"passed": BASELINE_PASSED, "failed": BASELINE_FAILED, "ignored": BASELINE_IGNORED}}
    )


def check_r5_baseline_verified(proof: dict) -> CheckResult:
    """R5: baseline_verified field is true."""
    bv = proof.get("baseline_verified", False)
    passed = proof.get("passed", -1)
    failed = proof.get("failed", -1)

    # Verify equivalence: baseline_verified == (passed == 226 and failed == 0)
    expected_bv = (passed == BASELINE_PASSED and failed == BASELINE_FAILED)
    consistent = bv == expected_bv

    return CheckResult(
        rule="R5",
        passed=bv and consistent,
        message="Baseline verified" if bv and consistent else f"R5 VIOLATED: baseline_verified={bv} but passed={passed}, failed={failed}",
        severity="CRITICAL",
        evidence={"baseline_verified": bv, "passed": passed, "failed": failed, "expected_bv": expected_bv, "consistent": consistent}
    )


def check_r6_test_count(passed: int) -> CheckResult:
    """R6: Test count >= baseline (monotonic)."""
    sufficient = passed >= BASELINE_PASSED

    return CheckResult(
        rule="R6",
        passed=sufficient,
        message=f"Test count maintained ({passed} >= {BASELINE_PASSED})" if sufficient else f"R6 VIOLATED: {passed} < {BASELINE_PASSED}",
        severity="HIGH",
        evidence={"passed": passed, "required_min": BASELINE_PASSED}
    )


def check_r6_strict(passed: int) -> CheckResult:
    """R6 strict: test count == baseline exactly (detects AV2 partial execution)."""
    exact = passed == BASELINE_PASSED

    return CheckResult(
        rule="R6_STRICT",
        passed=exact,
        message=f"Exact test count ({passed} == {BASELINE_PASSED})" if exact else f"AV2 DETECTED: Test count mismatch — expected={BASELINE_PASSED}, got={passed}",
        severity="CRITICAL",
        evidence={"passed": passed, "expected": BASELINE_PASSED, "gap": passed - BASELINE_PASSED}
    )


# ─────────────────────────────────────────────────────────────────
# AV Detection
# ─────────────────────────────────────────────────────────────────

def check_av2_partial_execution(passed: int, failed: int, ignored: int) -> CheckResult:
    """AV2: Detects partial test execution (cargo test --skip)."""
    # R6 strict catches exact count mismatch
    # Additional check: if failed == 0 but passed < 226, likely skipped
    is_partial = (failed == 0 and passed < BASELINE_PASSED)

    return CheckResult(
        rule="AV2",
        passed=not is_partial,
        message="No partial execution detected" if not is_partial else f"AV2 DETECTED: Possible partial execution — only {passed}/{BASELINE_PASSED} tests run",
        severity="CRITICAL",
        evidence={"passed": passed, "baseline": BASELINE_PASSED, "missing": BASELINE_PASSED - passed}
    )


def check_av6_ignore_bypass(repo_root=".", baseline_branch="origin/develop/v2.8.0"):
    """AV6: Full repo scan for #[ignore].

    Note: Total ignore count includes grandfathered ignores from v2.7.0.
    R2 (diff-based) already catches NEW ignores. AV6 provides total count
    for visibility — it is informational, not a hard violation.
    """
    result = subprocess.run(
        ["grep", "-R", "#\\[ignore", "--include=*.rs", "tests/", "crates/"],
        capture_output=True,
        text=True,
        cwd=repo_root
    )
    all_ignores = [l for l in result.stdout.splitlines() if l.strip()]

    return CheckResult(
        rule="AV6",
        passed=True,  # Informational only — R2 catches new ignores
        message=f"Found {len(all_ignores)} #[ignore] (grandfathered from v2.7.0; R2 monitors for new)",
        severity="INFO",
        evidence={
            "total_count": len(all_ignores),
            "note": "Total ignore count. R2 diff-check catches new ignores. AV6 is for visibility."
        }
    ), {"total": len(all_ignores)}


def check_av9_determinism(runs: list) -> CheckResult:
    """AV9: Non-deterministic test masking.

    Uses majority voting among VALID runs (parse_error=False).
    If >=2/3 runs agree on passed/failed, system is deterministic.
    Rationale: parallel test output can be non-deterministic by design
    (interleaved stdout); we care about actual test behavior,
    not output parsing stability.
    """
    valid = [r for r in runs if not r.parse_error]
    if len(valid) < 2:
        return CheckResult(
            rule="AV9",
            passed=True,
            message=f"AV9: Indeterminate — only {len(valid)} valid runs (need >=2). Treating as PASS.",
            severity="INFO",
            evidence={"total_runs": len(runs), "valid_runs": len(valid)}
        )

    # Count by (passed, failed)
    counts: dict = {}
    for r in valid:
        key = (r.passed, r.failed)
        counts[key] = counts.get(key, 0) + 1

    majority_count = max(counts.values())
    majority_key = max(counts, key=lambda k: counts[k])

    consistent = majority_count >= 2

    return CheckResult(
        rule="AV9",
        passed=consistent,
        message=f"AV9: {'Deterministic' if consistent else 'Non-deterministic'} — "
                f"{majority_count}/{len(valid)} runs agree on passed={majority_key[0]}, failed={majority_key[1]}",
        severity="MEDIUM" if not consistent else "INFO",
        evidence={
            "total_runs": len(runs),
            "valid_runs": len(valid),
            "consistent": consistent,
            "majority": {"passed": majority_key[0], "failed": majority_key[1], "votes": majority_count}
        }
    )


# ─────────────────────────────────────────────────────────────────
# Trust Assumption Checks
# ─────────────────────────────────────────────────────────────────

def check_trust_assumptions() -> List[CheckResult]:
    """T1-T6: All trust assumptions are ASSUMED (cannot verify externally)."""
    results = []

    t4_check = subprocess.run(
        ["python3", "-c", "import sys; sys.path.insert(0, 'scripts'); from audit.parser import parse_results_independent; print('OK')"],
        capture_output=True,
        text=True,
        cwd="."
    )

    results.append(CheckResult(
        rule="T4",
        passed=True,
        message="Trust assumptions are held (not technically verifiable)",
        severity="INFO",
        evidence={"note": "T1-T6 are trust assumptions, not verifiable within system"}
    ))

    return results


# ─────────────────────────────────────────────────────────────────
# Proof vs Reality (Core independent verification)
# ─────────────────────────────────────────────────────────────────

def check_proof_vs_reality(proof: dict, reality) -> CheckResult:
    """Compare proof artifact against independent test execution reality.

    This is the CORE check that detects AV4 (V tampering).
    If proof.passed != reality.passed, V was likely tampered with.
    """
    proof_passed = proof.get("passed")
    reality_passed = reality.passed
    proof_failed = proof.get("failed")
    reality_failed = reality.failed

    passed_match = proof_passed == reality_passed
    failed_match = proof_failed == reality_failed

    return CheckResult(
        rule="PROOF_VS_REALITY",
        passed=passed_match and failed_match,
        message="Proof matches independent execution" if (passed_match and failed_match) else f"AV4 ALERT: Proof says passed={proof_passed} but reality shows passed={reality_passed}",
        severity="CRITICAL",
        evidence={
            "proof": {"passed": proof_passed, "failed": proof_failed},
            "reality": {"passed": reality_passed, "failed": reality_failed},
            "passed_match": passed_match,
            "failed_match": failed_match
        }
    )
